### ISSUE TITLE
Edicts mapping

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#100]
Vic3 has decrees to which EU4 state edicts could be mapped.
- Advancement Effort => decree_promote_social_mobility
- Centralization Effort => decree_promote_national_values
- Defensive Edict => decree_elite_guard_training
- Encourage Development => decree_greener_grass_campaign
- Feudal De Jure Law => decree_violent_suppression
- Religion Enforced => decree_promote_national_values
- Edict of Absolutism => decree_violent_suppression
- Increased Enlistment => decree_elite_guard_training
- Protect Trade => decree_road_maintenance
- Enforce Religious Unity => decree_promote_national_values

**Comment by gawquon** [comment]
This would require finding some connection between an EU4 state and a Vic3 state or substate. Something like the EU4 state that ended up contributing the most to this V3 state or substate gets to decide the decree. But then the Authority capacity would have to be accounted for #20.

**Comment by Zemurin** [comment]
I'd say this is nominally an ok idea, but the reality is such things are best left to the players. While the edicts may map over, their meaning is completely different. A state with high uprising in eu4 may have zero in vic3, making the edict meaningless and wasteful. Ditto for advancement when there's no institution spread in vic3. Road maintenance is also useless if you're over infrastructure and not actively building..  so on and so on. Best under the player supervision, IMHO.

I'll close this issue as I don't think we'd gain anything meaningful from implementing this.
