### ISSUE TITLE
Culture generation from entire scratch

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#105]
See #81 and #74 for other details

Religion: a "census" should be done in Vic3 to find out the religion most pops of this given culture are praying to and assign it accordingly

Color: the following "work" should be used to define colours
- Is there a defined color in ```culture_colors.txt```? If yes, use the defined colour
- Is there a country defined as primary (from ```unions.txt```)? If yes, use the colour from this country
- Is there any country with this culture as primary? If yes, use the first country that is valid for this
- If all else fails, a colour will be generated by this formula: 
![image](https://user-images.githubusercontent.com/24550392/175342731-8e667b53-12b3-4cc7-b01e-e87555a1d337.png)

Name pools:
![image](https://user-images.githubusercontent.com/24550392/175342197-954fc5fb-37b7-4795-8162-7b1966bd72fd.png)
![image](https://user-images.githubusercontent.com/24550392/175342255-0500afca-5011-4be3-bbfe-b3097c764a2a.png)

**Comment by Zemurin** [comment]
This is implemented, cultures gain colors based on their names and features in a predetermined way so there is no need for a specific mapping file.
