### ISSUE TITLE
Chinese countries reassignment

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#117]
Any country that is of any of these Vic3 cultures (han, hakka, min, yue, manchu, miao, zhuang, yi, yue) _and_ of rank lower than Empire, should get tag-reassigned according to the state their capital is in in Vic3. If more tags have the same state as capital, only the first one gets tag-reassigned.

If there is only one Chinese country of Empire rank, it is reassigned as `CHI` (China). If there are more, the one with the mandate of Heaven. If neither has it, no tag-reassignement occurs with Empire-rank countries.

The configurable deciding to what tag reassign Chinese countries is named chinese_renamings.txt

**Comment by Zemurin** [comment]
There is no need for this, IMHO. After a mingexplosion, or after a player does manchu/qing and conquers china, they already have both the base name and culture of the nation unifying china.
