### ISSUE TITLE
Long country names

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#119]
The difference between short and long country names is obvious: _China_ vs. _The People's Republic of China_; _Germany_ vs. _Federal Republic of Germany_.

We may generate long country names for all tags by using custom localization. We may also consider "forcing" the long name on tags where a civil war is happening (so we don't get "Belgium vs. Belgium" incomprehensible stuff).

These generated long country names may be used for HoI4 as well.

The long country name in Vic3 would be summoned through three parts, namely `prefix`, `core`, `suffix`. `core` can be either the country's name or the country's adjective. The following list is not exhaustive, and is meant to provide ideas.
- Prefixes: [empty], Republic of, People's Democratic Republic of, Principality of, Commonwealth of, Kingdom of, Plurinational State of, Federative Republic of, People's Republic of, Union of, Arab Republic of, State of, Co-Operative Republic of, Islamic Republic of, Hashemite Kingdom of, Grand Duchy of, United, Federal Democratic Republic of, Sultanate of, Federation of, Independent State of, Democratic Socialist Republic of, Socialist Republic of
- Suffixes: [empty], People's Democratic Republic, Republic, States, Empire, Confederation, Arab Republic, Khanate, Reich, Soviet Republic, People's Republic, Soviet Socialist Republic

Grammar rules should also be taken in mind (articles, declensions, etc.) when eventually coding this in for Vic3

**Comment by IohannesIohannium** [comment]
See if it is possible to summon long forms through dynamic country names in case of civil wars, also without causing recursion.

Also consider the possibility to add a game rule to always use long forms.

**Comment by Zemurin** [comment]
I'm closing this as the base game shows no examples for fully fledged names. Germany is Germany (or German Empire), and the long-form names only show up for the first time in HoI4.

If at some point the game starts displaying "Union of Soviet Socialist Republics" instead of "Soviet Union", I'll reopen this.
