### ISSUE TITLE
Custom triggers needed for modding

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#132]
Output in `/common/scripted_triggers/99_colonialism.txt`:

## Colonial nation

```
is_colonial_nation = {
	OR = {
		AND = { tag = [ABC] is_subject_of = c:[XYZ] }
	}
}
```

The `AND = { tag = [ABC] is_subject_of = c:[XYZ] }` line should be repeated for each colonial nation. ABC is the colonial nation tag, XYZ is the overlord/mother country.

This trigger will be useful for vanilla flag sets that would need an additional form due to colonial reassignment tags (#125)

## Holy Roman Emperor

`is_colonial_nation = { c:[TAG] = ROOT }`, where TAG is the HRE

**Comment by Zemurin** [comment]
Closing as unnecessary. Colonial Cantons handle the flags, and we already export country_type = colonial for all colonial countries (independent or not).
