### ISSUE TITLE
Banned symbols - converter option

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#135]
Consider adding an option in the converter that would overwrite some symbols with a censured version thereof.

Symbols that are known to need censorship:
- Confederate war flag
- Swastikas, SS runes and Celtic crosses
- Flags of the Republic of China (Taiwan), Hong Kong and Tibet

**Comment by Froozigiusz** [comment]
If this feature would be implemented, I propose being able to select specific groups of icons that you want to be censored, as I don't think putting chinese sensitive flags beside Third Reich ones would be fair.

**Comment by Zemurin** [comment]
EU4 features no such symbols, and neither does Vic3. There is no need for this.
