### ISSUE TITLE
Religion and culture - splits and tolerance

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#138]
When assigning religions to a culture, _if_ there is any religion other than the main one that is >=30%, a new dynamic culture should be generated.
E.g.:
- Yugoslav culture census finds: 40% Orthodox, 30% Catholic, 25% Sunni, 5% other ones
- Results:
 - Yugoslav culture will be Orthodox
 - All Catholic Yugoslav pops will be in a new Catholicko-Yugoslav culture
 - All Sunni and other Yugoslav pops will be of Yugoslav culture

If no split can be done, _but_ the main religion is practiced by less than 50% of the POPs of that culture, a religious tolerance trait (yet to be coded in) will be assigned to the culture.

**Comment by Zemurin** [comment]
There are no game examples of such splits. Also, we risk fracturing the cultures even further. I don't think such a mechanism would be useful as religions do not fracture cultures - they just create pops of different religion.
