### ISSUE TITLE
Revise name lists transliterations in other languages

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#151]
Languages needing revision:
- [ ] Russian
- [ ] Chinese
- [ ] Japanese
- [ ] Korean
- [ ] Spanish (see _Fundeu_)
- [ ] Portuguese (see _Folha de São Paulo_)

**Comment by Zemurin** [comment]
Any review of existing localizations would be very much welcome. 

I personally do not intend to work on any loc-based issues, but any contributor can help with verification and expansion wherever needed.
