### ISSUE TITLE
Treaty Ports

### ISSUE THREAD

**Issue by ossumdud** [ParadoxGameConverters/EU4ToVic3#172]
So if a country in eu4 owns a singular province in a region in eu4, one idea when converting to split state was having an option to create treaty ports. When turning an eu4 state for a country into a vic3 state, it could look something like below:

vic3 state is unincorporated
if ( state AND autonomy < 50){
    make incorporated state
}else{
    if (owned provinces in region == 1){
        host country gets port province
        neighbor gets rest of provinces
        host port province becomes treaty port
    }
}

**Comment by gawquon** [comment]
Does a pre-game defined treaty port have to be the `port = "x93C3BC"` style province?

**Comment by Zemurin** [comment]
There iare a few specifics about treaty ports. They would need to be the only such Vic3 province (with is often difficult as 1 eu4 province can map to many Vic3 ones) - in the vic3 region - that is not the same region as Vic3 capital.

It would further need to be unincorporated as treaty ports can't be incorporated.

Use-cases for this would be very very specific and would rely heavily on custom province mappings (where we attempt to historically map Goa to Goa and no other province around it, for the sole purpose of generating a treaty port, if possible, for some nation).

EU4 for example doesn't have Hong Kong, but it does have some provinces suitable for this.

Step 1: Review the mappings, locate EU4-suitable treaty ports and make sure they map to a single Vic3 province.
Step 2: Add logic: "If owned by a nation with capital elsewhere, and who owns ONLY this province in Vic3 region, flag as treaty port + flag as unincorporated".

**Comment by Zemurin** [comment]
Addendum:

Yes, such a province MUST be a port, as defined by Vic3 map_data/state_regions, limiting the selection further.

**Comment by Zemurin** [comment]
Over time I have mapped most of the historical treaty ports from eu4 to vic3 even at the cost of somewhat inaccurate surrounding mappings. We can expand the mappings in time but more or less all of Asia, North Africa, and important European ports have been linked. Closing this issue.
