### ISSUE TITLE
Expansion of dynamic tags flagsets

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#180]
After #87 will be implemented, we can then consider expanding such flagsets.

This would require:
- [ ] Creating flag definition sets for **_each and every_** legacy code we use:
```
legacy_ABC = {
	flag_definition = {
		coa = legacy_ABC
		subject_canton = legacy_ABC
		allow_overlord_canton = yes
		priority = 1
	}
	flag_definition = {
		coa = legacy_ABC_monarchy
		subject_canton = legacy_ABC_monarchy
		allow_overlord_canton = yes			
		priority = 20
		trigger = { 
			coa_def_absolute_monarchy_flag_trigger = yes
		}
	}
	...
}
```
- [ ] Change the converter to generate dynamic tag sets in the following way instead: `[Vic3 tag] = { includes = [legacy code] }`

And then we can expand the legacy code flag definition sets by adding other cases (Christian theocracy, subject of ..., etc.)

**Comment by Zemurin** [comment]
This is implemented (to the ebest of my knowledge). All legacy_TAG_<government> flags are used if there is a matching country they can be assigned to.
