### ISSUE TITLE
Figure out PDX apportionment

### ISSUE THREAD

**Issue by gawquon** [ParadoxGameConverters/EU4toVic3#194]
When placing RGO buildings we need to know the max possible in the state. The split of a state's resources among it's substates is derived during runtime for Vic3. We need to know who gets the extra capacity.

| State Part | Actual Arable Land | Provinces | Land / Provinces  | Rounded Values |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Lübeck | 7  | 1 | 6.5  | 7  | 
| Holstein | 19 | 3 | 19.5 | 20  | 
| Schleswig | 26 | 4 | 26 | 26  | 
| SUM(Whole State)  | 52 | 8 | 52  | 53 | 

So why does Schleswig-Holstein round Lübeck up and Holstein down?

- Round up fewest provinces first?
- Round up first defined in state_regions/00_west_europe.txt?
- Round up alphabetically first?
- Something else?

**Comment by gawquon** [comment]
state_regions/00_west_europe.txt
---------------
```
STATE_SCHLESWIG_HOLSTEIN = {
    id = 66
    subsistence_building = "building_subsistence_farms"
    provinces = { "x00C060" "x60809F" "x64824C" "x78B203" "x804160" "xBFCC21" "xE000A0" "xE3C876" }
    city = "x64824C"
    port = "x60809F"
    farm = "x00C060"
    mine = "x00C060"
    wood = "x804160"
    arable_land = 52
    arable_resources = { "bg_rye_farms" "bg_livestock_ranches" }
    capped_resources = {
        bg_logging = 6
        bg_fishing = 6
    }
    naval_exit_id = 3019
}
```
history/states/00_states.txt
---------------
```
STATES = {
	s:STATE_SCHLESWIG_HOLSTEIN = {
		create_state = {
			country = c:HOL
			owned_provinces = { x804160 x64824C xE000A0 }
		}
		create_state = {
			country = c:LUB
			owned_provinces = { x60809F }
		}
		create_state = {
			country = c:SCH
			owned_provinces = { x00C060 x78B203 xE3C876 xBFCC21 }
		}
		
		add_homeland = danish
		add_homeland = north_german
	}
}
```

**Comment by ossumdud** [comment]
So attached is the spreadsheet I have on the state of saxony. There appears to be an optional modifier that I would guess distributes arable land and resources, but we don't know what the formula being used is. Important to note is that not all states have this modifer, such as Schleswig Holstein, and so the formula may differ for states without it.
[Vic3ProvinceLandAnalysis.xlsx](https://github.com/ParadoxGameConverters/EU4toVic3/files/10049226/Vic3ProvinceLandAnalysis.xlsx)

**Comment by ossumdud** [comment]
[Vic3ProvinceLandAnalysis.xlsx](https://github.com/ParadoxGameConverters/EU4toVic3/files/10049678/Vic3ProvinceLandAnalysis.xlsx)
Spreadsheet updated with Hannover and Schleswig-Holstein

**Comment by gawquon** [comment]
[Vic3ProvinceLandAnalysis.xlsx](https://github.com/ParadoxGameConverters/EU4toVic3/files/10053702/Vic3ProvinceLandAnalysis.xlsx)
More spreadsheet goodies. Tested some approximations. If we could get an approximation that always undercounts and never overcounts that would be more than sufficient for our purposes. As long as the true value is about one off of the approximated value when the true value has a magnitude ~<10. If there is space for 90 coal mines and we say there is only 70, that is fine.

**Comment by CaesarVincens** [comment]
From the defines:
```
SPLIT_STATE_MIN_LAND_SHARE = 0.05
SPLIT_STATE_DOMINANT_LAND_SHARE_THRESHOLD = 0.5	# States with more land share than this can use the region's name
SPLIT_STATE_PRIME_LAND_WEIGHT = 5.0
```

In case it helps

**Comment by gawquon** [comment]
So there isn't a min arable land value, just the minimum land share percent Caeser showed us in the defines. We can now predict resource splits in states with and without prime land.
![image](https://user-images.githubusercontent.com/71318452/203208813-315b89be-e19a-428b-8be8-5b6e30dbc7d3.jpg)

Resource splits in states with impassable provinces is still unaccounted for.

**Comment by CaesarVincens** [comment]
From my experience, impassible provinces only matter for army/front purposes. Is there some issue with how they apply to RGO/ag?

**Comment by gawquon** [comment]
Yes, only if there is a split state
![image](https://user-images.githubusercontent.com/71318452/203210487-4eed4529-022b-4dc6-a3bd-5db34d3a5b7a.png)
Sintang has 7 impassable provinces, and it's landshare is far closer to Sambas who only has 3 provinces and not Pontiak with a much closer 11.

**Comment by CaesarVincens** [comment]
Gotcha, if I find anything in the files that looks relevant, I'll let you know.

**Comment by gawquon** [comment]
Updated Spreadsheet with landshares - 
[Vic3ProvinceLandAnalysis.xlsx](https://github.com/ParadoxGameConverters/EU4toVic3/files/10063151/Vic3ProvinceLandAnalysis.xlsx)

**Comment by gawquon** [comment]
So there were two errors in our dataset. 

- Saxony the country has 6 prime provinces not 5
- Pontianak and Sintang's province numbers were switched. 

We now have the formula to landshare.
```math
\dfrac{\left( n_{i}\right) +\left( D-1\right) p_{i}-i_{i}}{\left( n_{total}\right) +\left( D-1\right) p_{total}-i_{total}}=\text{landshare}
\quad\quad
\begin{align}
n=\text{\# of provinces}\\
p=\text{\# of prime provinces}\\
i=\text{\# of impassible provinces}\\
D=\text{defines} = 5.0
\end{align}
```
Note that _n_ includes _p_ and _i_ within it: $n = \text{other} + \text{prime} + \text{impassible}$, _n_ is all provinces in a substate.

We still don't know why some .5s round up and others round down. The total of any resource is not preserved(The files say 52 coal, but the split states have 53.) Because of this, the issue screams floating point error to me.
