### ISSUE TITLE
Consider reading SPLIT_STATE_PRIME_LAND_WEIGHT from Vic3

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4ToVic3#209]
Used in EU4toV3/Source/V3World/ClayManager/StateLoader/State.cpp. If read from the game, it wouldn't need to be changed in code if changed in the game.

**Comment by gawquon** [comment]
List of used Defines
- INDIVIDUALS_PER_POP_INFRASTRUCTURE
- SPLIT_STATE_PRIME_LAND_WEIGHT
