### ISSUE TITLE
Laws mapping

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic3#21]
See dev diary https://forum.paradoxplaza.com/forum/developer-diary/victoria-3-dev-diary-7-laws.1483581/

**Comment by ossumdud** [comment]
[vic3_gov_reforms_outline (1).txt](https://github.com/ParadoxGameConverters/EU4toVic3/files/9913206/vic3_gov_reforms_outline.1.txt)
this is up to monarchy tier 4

**Comment by ossumdud** [comment]
[vic3_gov_reforms_outline (2).txt](https://github.com/ParadoxGameConverters/EU4toVic3/files/9913225/vic3_gov_reforms_outline.2.txt)
up to monarchy tier 4

**Comment by ossumdud** [comment]
[vic3_gov_reforms_outline (2).txt](https://github.com/ParadoxGameConverters/EU4toVic3/files/9913369/vic3_gov_reforms_outline.2.txt)
up to monarchy economic reforms

**Comment by ossumdud** [comment]
[vic3_gov_reforms_outline (2).txt](https://github.com/ParadoxGameConverters/EU4toVic3/files/9924201/vic3_gov_reforms_outline.2.txt)
Monarchy Outline almost ready for edits, just needs revolutionary states added
