### ISSUE TITLE
Couldn't find tech definition for: tech_bureaucracy

### ISSUE THREAD

**Issue by MediciPrime** [ParadoxGameConverters/EU4toVic3#330]
<img width="888" alt="error" src="https://user-images.githubusercontent.com/11708268/215303665-6c862235-9c36-40ec-95f4-7976fd8f365c.PNG">
Not sure why but I am getting this error.

**Comment by Zemurin** [comment]
This bug report is 
a) in the wrong place, 
b) missing any actionable information, and 
c) missing required files. 
Read the FAQ.
