### ISSUE TITLE
Suggestion: Total Development Influences Tech-Tree Advancement.

### ISSUE THREAD

**Issue by ericoulster** [ParadoxGameConverters/EU4ToVic3#366]
Hello,

I ported a couple of my old EU4 saves over to Vic3 and played them.

As someone who specifically enjoys taking low-tier non-European countries and making them into mid/high tier empires in EU4, I feel like the current technology system can sometimes negatively impact playability.

One mechanic that I think would be fun is to decide a nation's advancement in the tech tree based on their total cumulative development points.

The idea being that a nation with strongly developed infrastructure is likely going to have more advanced technologies in general.

Manpower would map to Military tech, Production to Production, and Base Tax to Society.

I am not sure if it would make more sense to reward these techs based on a ranking system, or based on the individual values for each dev point. Either way, this would be a way of giving a more substantial balance to non-European EU4 nations that were powerhouses, both "wide" and "tall".

**Comment by Zemurin** [comment]
We already use average development to set population wealth. Development itself has nothing to do with tech not is in any way related to cultural advances - in EU4 or Vic3.
Using absolute dev for anything would just ensure large countries get more tech and small - actual tall countries - do not.

If you disagree with how tech is distributed for non-european countries, either disable eurocentrism or edit westernization.txt.
