### ISSUE TITLE
Having cultures have different traits based on EU4 culture group changes

### ISSUE THREAD

**Issue by CarbonY26** [ParadoxGameConverters/EU4ToVic3#373]
In EU4: Vietnamese, Jurchen, Korean, Tibetan, and the Altaic group can Sinicize to be in the Chinese culture group. Is it possible to convert these cultures into their Victoria 3 equivalents while adding Chinese traits? 

Additionally, the British culture group will be able to move into the French culture group in the upcoming Domination DLC.

**Comment by Zemurin** [comment]
The current system fully supports mapping any culture to specific traits. So yes, all that's needed is adding appropriate lines to culture_trait_map.txt.

Feel free to edit it and expand the mappings.

**Comment by Zemurin** [comment]
Instead of having separate mapping leading to new cultures with these traits, we're using:
configurables/eu4_culture_new_mappings.txt
to dynamically alter vic3 cultures with appropriate traits in case any of the source cultures are present in pops.

**Comment by BetaCarotina** [comment]
I've tried to test changes to eu4_culture_new_mappings.txt, but the converter doesn't seem to detect the cultures, even ones that were already in this file. Is that why this issue was reopened?

**Comment by Zemurin** [comment]
> I've tried to test changes to eu4_culture_new_mappings.txt, but the converter doesn't seem to detect the cultures, even ones that were already in this file. Is that why this issue was reopened?

Yes, it's not plugged in yet.
