### ISSUE TITLE
Converter crash under unclear circumstances.

### ISSUE THREAD

**Issue by Binero** [ParadoxGameConverters/EU4ToVic3#385]
I am on the latest EU4 update and I just finished a multiplayer campaign with my friend. We want to convert our save to Victory 3 to continue the campaign.

Whenever we do not select "All - dead is dead" for the "Delete reusable" option, the convertor crashes without much useful information. 
![image](https://user-images.githubusercontent.com/6867251/234486605-b08e2028-e6bc-43e2-b67e-ae32fa539229.png)
[log.txt](https://github.com/ParadoxGameConverters/EU4ToVic3/files/11329621/log.txt)

**Comment by Idhrendur** [comment]
Please repost this on the forum thread, also uploading your save so it can be replicated: https://forum.paradoxplaza.com/forum/threads/eu4-to-vic3-converter-thread.1475054/

**Comment by Zemurin** [comment]
This likely has nothing to do with cultures since it crashes on economy.

What does "Delete reusable" mean?

As idhrendur said, I need the save to replicate.
