### ISSUE TITLE
Dynamic cross-converter stuff

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#42]
(Messages copied over from Discord, written by me, @IhateTrains and @Zemurin)

IhateTrains — Oggi alle 14:18
I was thinking, what if we allowed mods to provide their own configurables?
In case of IRToCK3, they could be in mod's "ImperatorToCK3/configurables/" directory
PDX' CK2 converter had this
Zemurin — Oggi alle 14:21
While nothing would make me happier than mod creators to provide compatches in any shape or form, the reality is... well. when was the last time any outside modder provided a patch for converter for their own mod?
Such things require a tighter cooperation like what extended mod family has for eu4
IhateTrains — Oggi alle 14:22
In case of Imperator, @TinWiz needed some culture mappings for his mod
Zemurin — Oggi alle 14:23
I'm saying I'm all for it. I'd be glad to see people pushing own configs, a sthat'd mean they're keeping an eye ontop of converter development
IhateTrains — Oggi alle 14:26
I know I can just do it in ImperatorToCK3, but it would be beneficial to have this somehow standardised among the converters
For example, we could agree on every converter's configurable files being in mod's <converter name>/confugurables directory
Also, to specify whether a file should replace or add to the converter one, we could add replace = 1/0 in the begging of the mod's one 
IhateTrains — Oggi alle 14:37
Every converter that wants to support this, ofc
Zemurin — Oggi alle 14:46
I see no reason not to do this, really.
but not before there's a single mod that wants to make use of such feature, at least for non-impToCK3
Iohannes — Oggi alle 15:37
I'd consider adding a (target game)_converter folder to be used for overriding our default settings for all converters
Iohannes — Oggi alle 16:00
We could also allow for more dynamic conversions without having to code in many scenarios
E.g. Timeline where Bavaria became French, so Bavarian is now a French culture: solving it through minor generated overrides, rather than having t code a specific Bavaroise culture
Or taking care of CK3 dynamic faiths and cultures
Iohannes — Oggi alle 22:16
As a sidenote, we could recycle the glossary also for this
E.g. set = { culture = bavarian pool = german named_after = "Bavaria" prim_tag = BAV }
Same for religions, provided enough shenanigans:
set = { religion = neocatholic group = christian prefix = "Neo-" named_after = "Catholicism" }
(Maybe we could also port over religious icons and rgb values)
Load order would be:
- Special mod overriding configurables (will have a starting line with $REPLACE if it's meant to replace it entirely)
- Default configs (if $REPLACE is not found)
- Hardcoded fallbacks
Iohannes — Oggi alle 22:29
In this case, we may have special "pool" mappings set
E.g.
link = { eu4 = franconian vic3 = north_german }
link = { pool = german vic3 = north_german region = north_germany_region }
Whereas, a non-specified pool mapping would self-generate:
Let Bavarian be pool = carthaginian. We do not set a mapping for this pool. We do however have a special "pools.txt" config that has name-pools, culture groups, etc. ranked by pool
Example:
(pools.txt)
link = {
   pool = carthaginian
   culture_group = punic
   male_names = { Hannibal Hasdrubal }
   last_names = { Barqa Dido }
   gfxculture = { mena_gfx }
}
Zemurin — Oggi alle 22:34
are we talking about names?
or cultures?
or both?
Iohannes — Oggi alle 22:34
Dynamic cultures
Zemurin — Oggi alle 22:34
for what game? eu4?
Iohannes — Oggi alle 22:34
And how they may be handled if not "merged back"
Vic3
Ck3 hybrid culture becomes generated EU4 culture, we say how EU4Vic3 will handle it
Iohannes — Oggi alle 22:35
Outputs in /common/cultures a bavarian.txt file with culture group punic, etc.
This is just a vague proposal now, but it may be a thought for later
Zemurin — Oggi alle 22:39
hmmm
yeah so.
sososo.
eu4tovic2 can't eat this
it needs mappings.
Iohannes — Oggi alle 22:39
That's why I said later, for Vic3
Zemurin — Oggi alle 22:39
for vic3, anything is possible, yeah
so in ck3toeu4 we generate a francobavarian culture, and place it in french group
(it can't be in both groups)
and we make the pool registry to know it came from french and bavarian
for purpose of names and such
Iohannes — Oggi alle 22:41
It came from French and got named after Bavaria (maybe with Franco- prefix)
Zemurin — Oggi alle 22:41
and in vic3 we can import through either mapping or create novel ones on the fly
Iohannes — Oggi alle 22:41
Yep
The prim_tag field is used for our "add national cores" stuff:
If we create Franco-Bavarian on the fly in Vic3, and we had set (EU4) BAV as prim_tag, we'll add (Vic3-equivalent) BAV's cores to all Franco-Bavarian land
Zemurin — Oggi alle 22:42
I'm more concerned about frabav culture in new world and other further migrations
Iohannes — Oggi alle 22:43
That will be its own "dynamic culture" feature
Zemurin — Oggi alle 22:43
thing is
with pools
all dynamic stuff can be inside
no need any more for yankee or dixie or any of our custom new world cultures
Iohannes — Oggi alle 22:43
Yep
Zemurin — Oggi alle 22:43
we can geenrate it all using pools
Iohannes — Oggi alle 22:44
We could simply tell it to make Yankees use Hungarian names
1. Culture X owns more than 5 provinces in New World, is NOT Native American*
2. Culture X is found out to own 75% or more land inside a defined Y region
3. Culture Z is thus split, name pool from culture X, name from defined Y region names (e.g. "Appalachian", could have "Dixie" defined if split from English) 
IF culture X does not own more than 75% or more land inside a given region (they may overlap, but first one valid is chosen), it'll spawn a colonial culture renamed to Neo-X (e.g. Neo-English) 
IF culture X does not own more than 5 provinces in New World, no split happens
No need to go look for all variants of "Australian" now, no matter if it's the Mamluks or Wales who gets the island
Culture X is, however, Vic3-based
So, North German colonial, instead of Franconian colonial, Prussian colonial, etc.
The "is NOT native American" is actually defined through a barred_from_colonizing.txt config, so we can list all stuff that should not be branching, like Aliens or Maori
Zemurin — Oggi alle 22:52
yeah. codifyling locations and rules
Iohannes — Oggi alle 22:53
Colonial_regions.txt:
link = { region = australia_region default_name = "Australia" province = 1 province = 2 province = 3 }
Colonial_regions_special_names.txt
link = { region = australia_region parent = north_german name = "Südreich" } # Südreicher culture
Zemurin — Oggi alle 22:55
one of the major issues I had so far with eu4tovic2 mappings is that the sorce and target regions were reversed
we looked at eu4 regions instead looking at vic2 regions
no small fault due to vic2 not having proper regions
Iohannes — Oggi alle 22:55
Names, in all this, of course, refer to the relative polity's name, but we'll always use adjectives (so we summon "Australia" to get "Australian")
Zemurin — Oggi alle 22:56
so when mapping eu4 all is well, but map voltaire and your regions no longer exist
I'm hoping to reverse this in vic3.
Iohannes — Oggi alle 22:56
Hopefully
Last step in this dynamic feast is the HoI4 part
Generating ideas? No biggie
Generating icons? We will find a way to link cultures to tags from which we may steal the flag
E.g. Franco-Bavarian:
- Has it a "nationality" tag defined? Yes, BAV. Use BAV_neutrality flag
Asdfg:
- Has it a "nationality" tag defined? No.
- Has it only one on-map tag with it as primary culture? If yes, use its neutral flag. If no, use the one with greatest country rank
Zemurin — Oggi alle 22:59
btw
speaking of, and I'm hoping this too will be fixed in vic3
when we assign national cores for every single culture we recognize, and we do recognize a ton of them - no assimilation happens
so say you own entirety of slovenia as austria
there was never an actual slovenia
but there are cores and suddenly slovenes have -20% assimilation chance (positive is in range 0.005%) disabling it
Iohannes — Oggi alle 23:01
Yeah, vanilla Vic2 had easier genocide mechanics assimilation stuff
Zemurin — Oggi alle 23:01
Thsi is a major issue btw
you can't not put those cores or poles wouldn't exist
they'd assimilate to german and russian
but if you put them, bye bye to actual assimialtion everywhere
Iohannes — Oggi alle 23:02
One thing is, maybe we should restrict where do we output such cores based on 1. cultural acceptance 2. not existence of tag on-map
Zemurin — Oggi alle 23:02
no difference
slovenia vs poland
one is dead other never existed
you need both cores but you also need assimilation mechanics
Iohannes — Oggi alle 23:03
Does Slovenia have an input EU4 tag?
Zemurin — Oggi alle 23:03
sure
I'm playing it right now
Immagine
Iohannes — Oggi alle 23:03
Can't we look up last time they were on map in conversion?
Zemurin — Oggi alle 23:04
we don't record that
in fact
game doesn't record that
Iohannes — Oggi alle 23:04
Last ruler, then
Zemurin — Oggi alle 23:04
it records when something is occupied, liberated, becomes a core, loses core, or changes religion or culture
Iohannes — Oggi alle 23:04
They do not change if a tag is dead
Zemurin — Oggi alle 23:04
nope, doesn't work
see ireland
england eats all tribes, there never was an ireland, but it's ireland that revolts
it's a very messy issue without a clear fix
Iohannes — Oggi alle 23:05
We can't even do shite about culture groups
Irish and English are cousins, Poles and Germans aren't, Austrians and Slovenes neither
Zemurin — Oggi alle 23:06
exactly, vic2 doesn't give a shit
Iohannes — Oggi alle 23:06
Anyway, should I turn my lengthy post about dynamic generation into a Github issue and to which repository?
Zemurin — Oggi alle 23:07
it's an eu4tovic3 issue
shove it there
it's undercooked but it'll remind me we don't do regular mappings any more at all
we still link cultures but their definitions come from pools
well, not even that
we should link "people living in bavaria who are distinct from others" to vic3 "culture that corresponds to what that culture uses for names"
that's assuming vic3 even has bavarians and not just north/south germans again
Iohannes — Oggi alle 23:09
North South Germans again
With the caveat that "Austrian" may be South German's new name OR it's own thing
Zemurin — Oggi alle 23:10
....
great.
that'll help things
Iohannes — Oggi alle 23:12
OR to Vic3 generated-on-the-fly culture
Zemurin — Oggi alle 23:12
yup
however we really must be careful
such autogeneration for everything means updating every single decision, event etc that relies on cultures
Iohannes — Oggi alle 23:13
Or using special triggers
And updating just their definitions
Zemurin — Oggi alle 23:14
you still have to shove the triggers into those definitions
and stuff will change a lot
it's not dead like vic2/hpm
Iohannes — Oggi alle 23:14
is_culture_bavarian = {
   primary_culture = north_german
   # Generated
   primary_culture = bavarian
}
And just replace the ol' "primary_culture = north_german" with "is_culture_bavarian = yes" in the other files once, in blankmod
Zemurin — Oggi alle 23:15
yes, but then for every update to the game we must stay vigilant
and watch for any changes
Iohannes — Oggi alle 23:15
A small price to pay /s
Zemurin — Oggi alle 23:15
sigh
Iohannes — Oggi alle 23:16
Hopefully we'll not need to change that many files

**Comment by Zemurin** [comment]
We mostly resolved all of cultural issues with fully dynamic culture transference and name pool transfer/use. Mods providing their own configurables is not something I'd ever expect or enforce.
