### ISSUE TITLE
Lose junior personal union as republic

### ISSUE THREAD

**Issue by Tbeabm** [ParadoxGameConverters/EU4ToVic3#430]
In EU4 you can have junior personal union members as republic and when converted, countries still have their junior personal union members in VIC3. However, once unpause the game these junior members are lost immediately.

I understand it's a scripped game mechanic for VIC3 when countries abolish monarchy they lose these peronal unions. Just wondering if anything can be done to keep them. Thanks.

**Comment by Zemurin** [comment]
Current EU4 behavior is a known "won't fix" bug. Having PU(s) as a republic causes the ruler to get random additional dynasty name which changes with every election, and overall the prospect IMO makes no sense. 

I don't intend to do anything about this in Vic3, which obviously doesn't support it.
