### ISSUE TITLE
Custom and revolutionary flag mapping

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#44]
See how to map EU4 custom flags' divisions of the fields (the background pattern, so to say), integrate color mappings from https://github.com/ParadoxGameConverters/EU4toVic3/issues/22

**Comment by IohannesIohannium** [comment]
Revolutionary tricolors would be output thus:

```
[TAG]_revolutionary = {
    pattern = "pattern_solid.tga"
    color1 = "[a]"

    colored_emblem = {
        texture = "ce_tricolor_vertical.dds"
        color1 = "[b]"
        color2 = "[c]"
    }
}
```

`TAG` is Vic3 tag, `a`, `b` and `c` are the three flag colours, converted through #22.

Example for Byzantium:
![image](https://user-images.githubusercontent.com/24550392/146582220-2dca1771-a6b2-4d76-8b0c-17dd8c0be84e.png)

Output would be:
```
BYZ_revolutionary = {
    pattern = "pattern_solid.tga"
    color1 = "purple"

    colored_emblem = {
        texture = "ce_tricolor_vertical.dds"
        color1 = "purpure"
        color2 = "purple"
    }
}
```

Expected in-game appearance would be*: 
![image](https://user-images.githubusercontent.com/24550392/146582377-8bdf3f56-aeb1-4817-9134-da41c75d931d.png)

* Mapping of custom colour 2 to purpure is to be revised

**Comment by Zemurin** [comment]
```Let a be the country colour, inserted as rgb { x y z }
Then extract b and c: b as the first metal (white or yellow) that appears in the normal blazon, c as the first non-metal. Default to white and black if nothing found
This is very complicated though, so I can understand this being lower than lowest priority, since we're essentially fixing uglyness that barely even appears```

**Comment by Zemurin** [comment]
We fully support crafting of rev flags from eu4 and their use in vic3.
