### ISSUE TITLE
Country name locs supplying through a config file

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#489]
A configurable `country_names.csv` would be used to add locs for country names in languages that do not exist in EU4. The structure of the file will be simply as follows: `STRING;Portuguese;Polish;Russian;Japanese;Chinese;Korean;Turkish;x`. String is based on the EU4 tag.

Example lines:
```
GOT;Gotlândia;Gotlandia;Готланд;ゴットラ゚ンド島;哥得蘭島;고틀란드섬;Gotland;x
GOT_ADJ;gotlandês;gotlandzk;гутнийск;ゴットラ゚ンド;哥得蘭;고틀란드;Gotlandi;x
```

**Comment by Zemurin** [comment]
I'd rather not do it like this. Every Vic3 supported language has a blankMod/localization subfolder and having the name lists over there makes much more sense and doesn't require any coding support.
