### ISSUE TITLE
Culture conversion leaves cultures native to the state(s) with no homelands

### ISSUE THREAD

**Issue by BetaCarotina** [ParadoxGameConverters/EU4ToVic3#530]
OK, should've elaborated why this can be bad. The feature works as intended, but removing homelands can shrink releasables and formables and make the game less enjoyable for some. Not an easy issue to work out

**Comment by Zemurin** [comment]
Not fixing for now for a variety of reasons. Feel free to reopen if there is an actual issue that needs solving.
