### ISSUE TITLE
(Flavour) East Asian transcription schemes

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic3#55]
As an example, the city of _Beijing_ could be written through different "orthographies":
- Pekin (exonym)
- Beijing (Pinyin, currently used)
- Pei-Ching (Wade-Giles, or English-based)
- Peiking (EFEO, or French-based)
- Beidjing (Lessing-Othmer, or German-based)
- Pej-t'ing (Czech customary transcription)
- Beycinğ (Turkish customary transcription)
- Бэйцзин/Beyczin (Palladius, or Russian-based)
- Pejćin (Polish customary transcription)
- Hokkyō (Japanese reading, could also be written in the West as *Hokkyou*, *Hokkyô*)
- Bắc Kinh (Vietnamese reading)
- Peitzin (Greco-Latin plausible transcription)

In theory we could make use of the GP system to determine which transliteration scheme would be used for Chinese locations. As an example, if China is a GP, Pinyin would be used; else, the highest ranking GP with a designed scheme would determine the orthography*. As an example, if England is No. 1, Wade-Giles would be used ("Pei-Ching"); if France, EFEO ("Peiking"). Localities known through exonyms or fixed customary transcriptions (like Hong Kong or Shigatze) would be left unchanged.

This, however, can _not_ be extended to character name pools, which should be kept in the same scheme as vanilla Vic3 uses.

* Russian localization, if in Vic3, would keep using the Palladius system nevertheless; Chinese localization, if in Vic3, would see no change.

**Comment by CarbonY26** [comment]
Would like to two additional readings because why not:

-  Bukgyeong (Korean Reading)
-  Bwzgingh  (Zhuang Reading which could be used for all Tai cultures)

**Comment by IohannesIohannium** [comment]
No renaming function seems to be existing for Vic3 as per now

**Comment by IohannesIohannium** [comment]
See #112 for additional ideas

**Comment by IohannesIohannium** [comment]
Impossible to implement due to forced staticity of hub names
