### ISSUE TITLE
Liberty desire can be converted 1 -> 1 as of 1.7

### ISSUE THREAD

**Issue by gawquon** [ParadoxGameConverters/EU4ToVic3#566]
Liberty desire in Vic 3 is now a thing and is not a calculated value, but a value with state. The default is 50 as set in the defines.

**Comment by Zemurin** [comment]
Trouble is, liberty desire in EU4 is a calced value and we can't recreate it as it depends on all the factors (FL power projections, ideas, age modifiers, current diplorep etc etc.)

**Comment by gawquon** [comment]
The value appears to be cached in recent version of EU4. 
![c0](https://github.com/user-attachments/assets/56dd679c-0f5b-4aa2-8b43-6e6771d4fe38)
![c1](https://github.com/user-attachments/assets/dda6e419-f288-4ca2-b7b5-98f0d7587540)
