### ISSUE TITLE
Languages with no sources - Fallback

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#70]
There are some languages with no EU4 source. In such a case, the best would be to copy the tag's name from English in parentheses and "build" some adjective-ish form for it. "France" is here used as an example loc.

* PORTUGUESE Name `(France)`, Adjective `de (France)`
* JAPANESE Name and adjective `(France)`
* KOREAN Name and adjective `(France)`
* POLISH Name `(France)`, Adjective `(France)sk`
* RUSSIAN Name `(France)`, Adjective `(France)ск`
* CHINESE Name and adjective `(France)`
* TURKISH Name and adjective `(France)`

This should be understood to be a fallback solution, until locs are supplied

**Comment by Zemurin** [comment]
No, I don't intend to provide loc support for anything other than English in any capacity other than "most basic". It's not worth our time and looking at EU4's dynamic_locs_FR, even Tinto has a horrible time at it using people emplyed for that very purpose.
