### ISSUE TITLE
Tech conversion

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic3#83]
Each country has a file as `/common/history/countries/[TAG] - [Name].txt`, whose structure has the following:

```
COUNTRIES = {
	c:[TAG] = {
		effect_starting_technology_tier_[x]_tech = yes
		[other scripted effect] = yes
		active_law = law_type:[law string]

		ig:[interest group] = {
			add_ideology = [ideology name]
			set_interest_group_name = [ideology name]
		}
	}
}
```

`effect_starting_technology_tier_[x]_tech` has numbers from 1 (most advanced) to 7 (least advanced). An average number of total techs should be calculated from all EU4 Western and Eastern tech group countries. This average number we'll call α. Then, we find the country with the max amount of EU4 techs unlocked, and this number should be called β.
The tech tier is thus calculated by the following formula, where γ represents a tag's total number of unlocked techs.
![image](https://user-images.githubusercontent.com/24550392/173177838-71ebafa1-d701-436d-a94d-77aec21c1bbc.png)
The result should be rounded to the nearest integer.
In cases where α and β are the same (so a division by zero would happen), all Western and Eastern tags get tier 3, all non-decentralized other tags get tier 5, all decentralized tags get tier 7.

**Comment by gawquon** [comment]
Recording as a Vanilla benchmark. #236

## Tier 1 - the cutting edge Western powers
Just these 5 nations.
- France
- Britain
- USA
- Prussia
- Belgium
## Tier 2 - advanced European and American powers
48 Western nations in total.
- Austria
- Prussia
- Sweden
- Dutch East Indies
- HRE States
- British Colonies
## Tier 3 - backwards European and American powers
41 nations total, Western world + Egypt\
Mostly non-USA New World, Eastern European, Italian, and Iberian

- Spain
- Sicily
- Russia
- Mexico
- Egypt
- Texas
- Wallachia
- Brazil
- Liberia
- Papal States
## Tier 4 - most unrecognized nations and very backwards European powers
83 nations in total, most of the centralized non-western world

- Ottoman Empire
- Greece
- United Tribes (UK Subject)
- Abu Dhabi
- Burma
- Bhutan
- Dai Viet
- China
- Japan
- Korea
- Persia
- Morocco
- Indian Territory (USA Subject)
## Tier 5 - very backwards centralized powers
30 nationals in total, West/East Africa and a couple decentralized Kiwis

- Kaffa
- Kongo
- Massina
- Tigray
- Ngati Toa (Decentalized Kiwi)
## Tier 6 - decentralized countries with organized armies, extremely backwards centralized powers
51 nations in total, Much of Central/South Africa, America natives

- Pawnee
- Rwanda
- Zulu
- Kazakhstan
- Gurani
## Tier 7 - Decentralized countries with no technology
55 nationas in total, all decentralized\
Mostly Pacific/East Asian decentralized, plus some Africa

- Ainu
- Herero
- Jolof
- Luba
- Kru
- Micronesia
- Sakhalin
- Sulawesi
