### ISSUE TITLE
Legacy flag generation

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#87]
Initial support for EU4Vic2 library would use the following structure for each generated polity in `common/flag_definitions/00_flag_definitions.txt`

```
[Vic3 tag] = {
	flag_definition = {
		coa = legacy_[XYZ]
		subject_canton = legacy_[XYZ]
		allow_overlord_canton = yes
		priority = 1
	}
	flag_definition = {
		coa = legacy_[XYZ]_monarchy
		subject_canton = legacy_[XYZ]_monarchy
		allow_overlord_canton = yes			
		priority = 20
		trigger = { 
			coa_def_absolute_monarchy_flag_trigger = yes
		}
	}	
	flag_definition = {
		coa = legacy_[XYZ]_republic
		subject_canton = legacy_[XYZ]_republic
		priority = 10
		trigger = { 
			coa_def_republic_flag_trigger = yes
		}
	}	
	flag_definition = {
		coa = legacy_[XYZ]_communist
		subject_canton = legacy_[XYZ]_communist
		allow_overlord_canton = yes			
		priority = 20
		trigger = { 
			coa_def_communist_flag_trigger = yes
		}
	}	
	flag_definition = {
		coa = legacy_[XYZ]_fascist
		subject_canton = legacy_[XYZ]_fascist
		allow_overlord_canton = yes			
		priority = 20
		trigger = { 
			coa_def_fascist_flag_trigger = yes
		}
	}	
}
```
[XYZ] is the flag code we assign the tag, which it can be the same as the Vic3 final tag (`AAC` for Aachen) or a CK3 title code (`d_northumberland`)

**Comment by IohannesIohannium** [comment]
Note: Textured emblems _may not be supported_ initially

**Comment by IohannesIohannium** [comment]
The configurable `flag_block.txt` says for which tags these flag definition lines must NOT be output.
For the ones that can be output, the flag-code is thus understood:
- If the country is matched with a CK3 title, use it
- If not, use the country's Vic3 tag (not to use, however, for X## countries)

**Comment by IohannesIohannium** [comment]
Remind to myself: add a readme to explain how to add new flags to the library, both as images and as blazons

**Comment by Zemurin** [comment]
We fully support use and reuse of legacy flags via country_mappings.txt's `flag = TAG` system.
