### ISSUE TITLE
Diplomatic relations conversion

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic3#90]
Output in `/common/history/diplomacy/` folder

# Alliances (file `00_defensive_pacts.txt`)
Structure for each entry
```
DIPLOMACY = {
	c:[ABC] = {
		create_diplomatic_pact = {
			country = c:[XYZ]
			type = alliance
		}
	}
}
```
Guarantees are also output in this same file, but with the following structure
```
DIPLOMACY = {
	c:[Guaranteed country] = {
		create_diplomatic_pact = {
			country = c:[Patron country]
			type = defensive_pact
		}
	}
}
```

# Customs unions (file `00_customs_union.txt`)
Best blanked until a decent translation from EU4 mechanics is found

# Favors (file `00_favors.txt`)
Currently blanked as hard to translate from EU4

# Relations (file `00_relations.txt`)
Inside a big `DIPLOMACY = { ... }` bracket, each country has entries as follow:
```
	c:[TAG] = {
		set_relations = { country = c:[ABC] value = [num] }
		set_relations = { country = c:[XYZ] value = [num] }
		...
	}
```
This translates to EU4 country opinions

# Rivalries (file `00_rivalries.txt`)
Structure for each entry:
```
DIPLOMACY = {
	c:[ABC] = {
		create_diplomatic_pact = {
			country = c:[XYZ]
			type = rivalry
		}
	}
}
```

# Subjects (file `00_subject_relationships.txt`)
Structure for each entry:
```
DIPLOMACY = {
	c:[Master tag] = {
		create_diplomatic_pact = {
			country = c:[Subject tag]
			type = [puppet/personal_union/protectorate/dominion/tributary/vassal]
		}
	}
}
```
Configurable `agreement_types.txt` defines what type of subject relationship it is

# Truces (file `00_truces.txt`)
Structure for each entry:
```
DIPLOMACY = {
	c:[ABC] = {
		create_truce = {
			country = c:[XYZ]
			months = [num]
		}
	}	
}
```

# Increasing relationship (to-be-created `99_converter.txt`)
Used for EU4 improve relations mechanic to be translated into Vic3
```
DIPLOMACY = {
	c:[ABC] = {
		create_diplomatic_pact = {
			country = c:[XYZ]
			type = increase_relations
		}
	}
}
```

**Comment by gawquon** [comment]
Vic 3 nations are tech locked to only one ally until great war era
