### ISSUE TITLE
Unreleasable countries

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#95]
In their country definition entry, the following line needs to be added: `valid_as_home_country_for_separatists = { always = no }`

**Comment by Zemurin** [comment]
Aside for BYZ, in vic3 there are no unreleasable countries as there are no cores. And we're not introducing new formables so there's little need for this, for the moment. will reopen if we even introduce new formables (HRE? Rome?).
