### ISSUE TITLE
Characters generation

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4ToVic3#96]
Output in `/common/history/characters/[TAG] - [Country].txt`, inside a big CHARACTERS = { c:[TAG] = { ... } } double-bracket.
Each entry has such syntax:
		create_character = {
```
			first_name = [localized string]
			last_name = [localized string]
			[ruler/heir/is_admiral/is_general/politician] = yes
			noble = [yes/no] # No idea how to get this from EU4 mechanics yet
			birth_date = [yyyy.mm.dd]
			culture=cu:[character's culture, we should default to country's primary if unknown]
			interest_group = random
			traits = {
				[...]
			}
			on_created = { # This to be output if the character is married
				set_variable = is_married
			}
		}	
```
Politician should be used to convert all advisors of a country from EU4

**Comment by gawquon** [comment]
anyone can have the field `ideology = random`
(Only matters if they are/become an IG leader)

generals/admirals have the additional fields of
```
hq = [strategic_region]
commander_rank = [rank]
```

**Comment by gawquon** [comment]
For large countries, all generals should not be in the same strategic region. They would be unable to command troops from other regions and would split the troops that are in one region. Until a military rework is done generals also can not move hqs in game. Retiring existing generals costs IG support, so the player or AI can't just easily fix this by firing some and hiring new ones.
